// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/repository/feedback_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/repository/feedback_repository.go -destination=mocks/core/ports/repository/feedback_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	feedback "softpharos/internal/core/domain/feedback"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackRepository is a mock of FeedbackRepository interface.
type MockFeedbackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedbackRepositoryMockRecorder is the mock recorder for MockFeedbackRepository.
type MockFeedbackRepositoryMockRecorder struct {
	mock *MockFeedbackRepository
}

// NewMockFeedbackRepository creates a new mock instance.
func NewMockFeedbackRepository(ctrl *gomock.Controller) *MockFeedbackRepository {
	mock := &MockFeedbackRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackRepository) EXPECT() *MockFeedbackRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeedbackRepository) Create(ctx context.Context, arg1 *feedback.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeedbackRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedbackRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockFeedbackRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeedbackRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeedbackRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockFeedbackRepository) GetAll(ctx context.Context) ([]feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFeedbackRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFeedbackRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockFeedbackRepository) GetByID(ctx context.Context, id int) (*feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFeedbackRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFeedbackRepository)(nil).GetByID), ctx, id)
}

// GetByMilestoneID mocks base method.
func (m *MockFeedbackRepository) GetByMilestoneID(ctx context.Context, milestoneID int) ([]feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMilestoneID", ctx, milestoneID)
	ret0, _ := ret[0].([]feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMilestoneID indicates an expected call of GetByMilestoneID.
func (mr *MockFeedbackRepositoryMockRecorder) GetByMilestoneID(ctx, milestoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMilestoneID", reflect.TypeOf((*MockFeedbackRepository)(nil).GetByMilestoneID), ctx, milestoneID)
}

// Update mocks base method.
func (m *MockFeedbackRepository) Update(ctx context.Context, arg1 *feedback.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFeedbackRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeedbackRepository)(nil).Update), ctx, arg1)
}
