// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/repository/reaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/repository/reaction_repository.go -destination=mocks/core/ports/repository/reaction_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	reaction "softpharos/internal/core/domain/reaction"

	gomock "go.uber.org/mock/gomock"
)

// MockReactionRepository is a mock of ReactionRepository interface.
type MockReactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReactionRepositoryMockRecorder
	isgomock struct{}
}

// MockReactionRepositoryMockRecorder is the mock recorder for MockReactionRepository.
type MockReactionRepositoryMockRecorder struct {
	mock *MockReactionRepository
}

// NewMockReactionRepository creates a new mock instance.
func NewMockReactionRepository(ctrl *gomock.Controller) *MockReactionRepository {
	mock := &MockReactionRepository{ctrl: ctrl}
	mock.recorder = &MockReactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReactionRepository) EXPECT() *MockReactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReactionRepository) Create(ctx context.Context, arg1 *reaction.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReactionRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReactionRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockReactionRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReactionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReactionRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockReactionRepository) GetAll(ctx context.Context) ([]reaction.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]reaction.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockReactionRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockReactionRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockReactionRepository) GetByID(ctx context.Context, id int) (*reaction.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*reaction.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReactionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReactionRepository)(nil).GetByID), ctx, id)
}

// GetByMilestoneID mocks base method.
func (m *MockReactionRepository) GetByMilestoneID(ctx context.Context, milestoneID int) ([]reaction.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMilestoneID", ctx, milestoneID)
	ret0, _ := ret[0].([]reaction.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMilestoneID indicates an expected call of GetByMilestoneID.
func (mr *MockReactionRepositoryMockRecorder) GetByMilestoneID(ctx, milestoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMilestoneID", reflect.TypeOf((*MockReactionRepository)(nil).GetByMilestoneID), ctx, milestoneID)
}

// Update mocks base method.
func (m *MockReactionRepository) Update(ctx context.Context, arg1 *reaction.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReactionRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReactionRepository)(nil).Update), ctx, arg1)
}
