// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/repository/deliverable_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/repository/deliverable_repository.go -destination=mocks/core/ports/repository/deliverable_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	deliverable "softpharos/internal/core/domain/deliverable"

	gomock "go.uber.org/mock/gomock"
)

// MockDeliverableRepository is a mock of DeliverableRepository interface.
type MockDeliverableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliverableRepositoryMockRecorder
	isgomock struct{}
}

// MockDeliverableRepositoryMockRecorder is the mock recorder for MockDeliverableRepository.
type MockDeliverableRepositoryMockRecorder struct {
	mock *MockDeliverableRepository
}

// NewMockDeliverableRepository creates a new mock instance.
func NewMockDeliverableRepository(ctrl *gomock.Controller) *MockDeliverableRepository {
	mock := &MockDeliverableRepository{ctrl: ctrl}
	mock.recorder = &MockDeliverableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliverableRepository) EXPECT() *MockDeliverableRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeliverableRepository) Create(ctx context.Context, arg1 *deliverable.Deliverable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeliverableRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeliverableRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockDeliverableRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeliverableRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeliverableRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockDeliverableRepository) GetAll(ctx context.Context) ([]deliverable.Deliverable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]deliverable.Deliverable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDeliverableRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDeliverableRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockDeliverableRepository) GetByID(ctx context.Context, id int) (*deliverable.Deliverable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*deliverable.Deliverable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeliverableRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeliverableRepository)(nil).GetByID), ctx, id)
}

// GetByMilestoneID mocks base method.
func (m *MockDeliverableRepository) GetByMilestoneID(ctx context.Context, milestoneID int) ([]deliverable.Deliverable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMilestoneID", ctx, milestoneID)
	ret0, _ := ret[0].([]deliverable.Deliverable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMilestoneID indicates an expected call of GetByMilestoneID.
func (mr *MockDeliverableRepositoryMockRecorder) GetByMilestoneID(ctx, milestoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMilestoneID", reflect.TypeOf((*MockDeliverableRepository)(nil).GetByMilestoneID), ctx, milestoneID)
}

// Update mocks base method.
func (m *MockDeliverableRepository) Update(ctx context.Context, arg1 *deliverable.Deliverable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeliverableRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeliverableRepository)(nil).Update), ctx, arg1)
}
