// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/repository/milestone_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/repository/milestone_repository.go -destination=mocks/core/ports/repository/milestone_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	milestone "softpharos/internal/core/domain/milestone"

	gomock "go.uber.org/mock/gomock"
)

// MockMilestoneRepository is a mock of MilestoneRepository interface.
type MockMilestoneRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMilestoneRepositoryMockRecorder
	isgomock struct{}
}

// MockMilestoneRepositoryMockRecorder is the mock recorder for MockMilestoneRepository.
type MockMilestoneRepositoryMockRecorder struct {
	mock *MockMilestoneRepository
}

// NewMockMilestoneRepository creates a new mock instance.
func NewMockMilestoneRepository(ctrl *gomock.Controller) *MockMilestoneRepository {
	mock := &MockMilestoneRepository{ctrl: ctrl}
	mock.recorder = &MockMilestoneRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMilestoneRepository) EXPECT() *MockMilestoneRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMilestoneRepository) Create(ctx context.Context, arg1 *milestone.Milestone) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMilestoneRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMilestoneRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockMilestoneRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMilestoneRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMilestoneRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockMilestoneRepository) GetAll(ctx context.Context) ([]milestone.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]milestone.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMilestoneRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMilestoneRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockMilestoneRepository) GetByID(ctx context.Context, id int) (*milestone.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*milestone.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMilestoneRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMilestoneRepository)(nil).GetByID), ctx, id)
}

// GetByProjectID mocks base method.
func (m *MockMilestoneRepository) GetByProjectID(ctx context.Context, projectID int) ([]milestone.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]milestone.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectID indicates an expected call of GetByProjectID.
func (mr *MockMilestoneRepositoryMockRecorder) GetByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectID", reflect.TypeOf((*MockMilestoneRepository)(nil).GetByProjectID), ctx, projectID)
}

// Update mocks base method.
func (m *MockMilestoneRepository) Update(ctx context.Context, arg1 *milestone.Milestone) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMilestoneRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMilestoneRepository)(nil).Update), ctx, arg1)
}
