// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/repository/project_member_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/repository/project_member_repository.go -destination=mocks/core/ports/repository/project_member_repository_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	project_member "softpharos/internal/core/domain/project_member"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectMemberRepository is a mock of ProjectMemberRepository interface.
type MockProjectMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectMemberRepositoryMockRecorder is the mock recorder for MockProjectMemberRepository.
type MockProjectMemberRepositoryMockRecorder struct {
	mock *MockProjectMemberRepository
}

// NewMockProjectMemberRepository creates a new mock instance.
func NewMockProjectMemberRepository(ctrl *gomock.Controller) *MockProjectMemberRepository {
	mock := &MockProjectMemberRepository{ctrl: ctrl}
	mock.recorder = &MockProjectMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMemberRepository) EXPECT() *MockProjectMemberRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectMemberRepository) Create(ctx context.Context, projectMember *project_member.ProjectMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, projectMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectMemberRepositoryMockRecorder) Create(ctx, projectMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectMemberRepository)(nil).Create), ctx, projectMember)
}

// Delete mocks base method.
func (m *MockProjectMemberRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectMemberRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectMemberRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockProjectMemberRepository) GetAll(ctx context.Context) ([]project_member.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]project_member.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProjectMemberRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProjectMemberRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockProjectMemberRepository) GetByID(ctx context.Context, id int) (*project_member.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*project_member.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectMemberRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectMemberRepository)(nil).GetByID), ctx, id)
}

// GetByProjectID mocks base method.
func (m *MockProjectMemberRepository) GetByProjectID(ctx context.Context, projectID int) ([]project_member.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]project_member.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectID indicates an expected call of GetByProjectID.
func (mr *MockProjectMemberRepositoryMockRecorder) GetByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectID", reflect.TypeOf((*MockProjectMemberRepository)(nil).GetByProjectID), ctx, projectID)
}

// Update mocks base method.
func (m *MockProjectMemberRepository) Update(ctx context.Context, projectMember *project_member.ProjectMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, projectMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectMemberRepositoryMockRecorder) Update(ctx, projectMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectMemberRepository)(nil).Update), ctx, projectMember)
}
