// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services/auth_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services/auth_service.go -destination=mocks/core/ports/services/auth_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	user "softpharos/internal/core/domain/user"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// AuthenticateWithGoogle mocks base method.
func (m *MockAuthService) AuthenticateWithGoogle(ctx context.Context, idToken string) (*user.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateWithGoogle", ctx, idToken)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AuthenticateWithGoogle indicates an expected call of AuthenticateWithGoogle.
func (mr *MockAuthServiceMockRecorder) AuthenticateWithGoogle(ctx, idToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateWithGoogle", reflect.TypeOf((*MockAuthService)(nil).AuthenticateWithGoogle), ctx, idToken)
}
