// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services/deliverable_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services/deliverable_service.go -destination=mocks/core/ports/services/deliverable_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	deliverable "softpharos/internal/core/domain/deliverable"

	gomock "go.uber.org/mock/gomock"
)

// MockDeliverableService is a mock of DeliverableService interface.
type MockDeliverableService struct {
	ctrl     *gomock.Controller
	recorder *MockDeliverableServiceMockRecorder
	isgomock struct{}
}

// MockDeliverableServiceMockRecorder is the mock recorder for MockDeliverableService.
type MockDeliverableServiceMockRecorder struct {
	mock *MockDeliverableService
}

// NewMockDeliverableService creates a new mock instance.
func NewMockDeliverableService(ctrl *gomock.Controller) *MockDeliverableService {
	mock := &MockDeliverableService{ctrl: ctrl}
	mock.recorder = &MockDeliverableServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliverableService) EXPECT() *MockDeliverableServiceMockRecorder {
	return m.recorder
}

// CreateDeliverable mocks base method.
func (m *MockDeliverableService) CreateDeliverable(ctx context.Context, arg1 *deliverable.Deliverable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeliverable", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeliverable indicates an expected call of CreateDeliverable.
func (mr *MockDeliverableServiceMockRecorder) CreateDeliverable(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeliverable", reflect.TypeOf((*MockDeliverableService)(nil).CreateDeliverable), ctx, arg1)
}

// DeleteDeliverable mocks base method.
func (m *MockDeliverableService) DeleteDeliverable(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeliverable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeliverable indicates an expected call of DeleteDeliverable.
func (mr *MockDeliverableServiceMockRecorder) DeleteDeliverable(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeliverable", reflect.TypeOf((*MockDeliverableService)(nil).DeleteDeliverable), ctx, id)
}

// GetAllDeliverables mocks base method.
func (m *MockDeliverableService) GetAllDeliverables(ctx context.Context) ([]deliverable.Deliverable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDeliverables", ctx)
	ret0, _ := ret[0].([]deliverable.Deliverable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDeliverables indicates an expected call of GetAllDeliverables.
func (mr *MockDeliverableServiceMockRecorder) GetAllDeliverables(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDeliverables", reflect.TypeOf((*MockDeliverableService)(nil).GetAllDeliverables), ctx)
}

// GetDeliverableByID mocks base method.
func (m *MockDeliverableService) GetDeliverableByID(ctx context.Context, id int) (*deliverable.Deliverable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliverableByID", ctx, id)
	ret0, _ := ret[0].(*deliverable.Deliverable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliverableByID indicates an expected call of GetDeliverableByID.
func (mr *MockDeliverableServiceMockRecorder) GetDeliverableByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliverableByID", reflect.TypeOf((*MockDeliverableService)(nil).GetDeliverableByID), ctx, id)
}

// GetDeliverablesByMilestoneID mocks base method.
func (m *MockDeliverableService) GetDeliverablesByMilestoneID(ctx context.Context, milestoneID int) ([]deliverable.Deliverable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliverablesByMilestoneID", ctx, milestoneID)
	ret0, _ := ret[0].([]deliverable.Deliverable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliverablesByMilestoneID indicates an expected call of GetDeliverablesByMilestoneID.
func (mr *MockDeliverableServiceMockRecorder) GetDeliverablesByMilestoneID(ctx, milestoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliverablesByMilestoneID", reflect.TypeOf((*MockDeliverableService)(nil).GetDeliverablesByMilestoneID), ctx, milestoneID)
}

// UpdateDeliverable mocks base method.
func (m *MockDeliverableService) UpdateDeliverable(ctx context.Context, arg1 *deliverable.Deliverable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeliverable", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeliverable indicates an expected call of UpdateDeliverable.
func (mr *MockDeliverableServiceMockRecorder) UpdateDeliverable(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeliverable", reflect.TypeOf((*MockDeliverableService)(nil).UpdateDeliverable), ctx, arg1)
}
