// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services/milestone_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services/milestone_service.go -destination=mocks/core/ports/services/milestone_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	milestone "softpharos/internal/core/domain/milestone"

	gomock "go.uber.org/mock/gomock"
)

// MockMilestoneService is a mock of MilestoneService interface.
type MockMilestoneService struct {
	ctrl     *gomock.Controller
	recorder *MockMilestoneServiceMockRecorder
	isgomock struct{}
}

// MockMilestoneServiceMockRecorder is the mock recorder for MockMilestoneService.
type MockMilestoneServiceMockRecorder struct {
	mock *MockMilestoneService
}

// NewMockMilestoneService creates a new mock instance.
func NewMockMilestoneService(ctrl *gomock.Controller) *MockMilestoneService {
	mock := &MockMilestoneService{ctrl: ctrl}
	mock.recorder = &MockMilestoneServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMilestoneService) EXPECT() *MockMilestoneServiceMockRecorder {
	return m.recorder
}

// CreateMilestone mocks base method.
func (m *MockMilestoneService) CreateMilestone(ctx context.Context, arg1 *milestone.Milestone) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMilestone", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMilestone indicates an expected call of CreateMilestone.
func (mr *MockMilestoneServiceMockRecorder) CreateMilestone(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMilestone", reflect.TypeOf((*MockMilestoneService)(nil).CreateMilestone), ctx, arg1)
}

// DeleteMilestone mocks base method.
func (m *MockMilestoneService) DeleteMilestone(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMilestone", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMilestone indicates an expected call of DeleteMilestone.
func (mr *MockMilestoneServiceMockRecorder) DeleteMilestone(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMilestone", reflect.TypeOf((*MockMilestoneService)(nil).DeleteMilestone), ctx, id)
}

// GetAllMilestones mocks base method.
func (m *MockMilestoneService) GetAllMilestones(ctx context.Context) ([]milestone.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMilestones", ctx)
	ret0, _ := ret[0].([]milestone.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMilestones indicates an expected call of GetAllMilestones.
func (mr *MockMilestoneServiceMockRecorder) GetAllMilestones(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMilestones", reflect.TypeOf((*MockMilestoneService)(nil).GetAllMilestones), ctx)
}

// GetMilestoneByID mocks base method.
func (m *MockMilestoneService) GetMilestoneByID(ctx context.Context, id int) (*milestone.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMilestoneByID", ctx, id)
	ret0, _ := ret[0].(*milestone.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMilestoneByID indicates an expected call of GetMilestoneByID.
func (mr *MockMilestoneServiceMockRecorder) GetMilestoneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMilestoneByID", reflect.TypeOf((*MockMilestoneService)(nil).GetMilestoneByID), ctx, id)
}

// GetMilestonesByProjectID mocks base method.
func (m *MockMilestoneService) GetMilestonesByProjectID(ctx context.Context, projectID int) ([]milestone.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMilestonesByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]milestone.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMilestonesByProjectID indicates an expected call of GetMilestonesByProjectID.
func (mr *MockMilestoneServiceMockRecorder) GetMilestonesByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMilestonesByProjectID", reflect.TypeOf((*MockMilestoneService)(nil).GetMilestonesByProjectID), ctx, projectID)
}

// UpdateMilestone mocks base method.
func (m *MockMilestoneService) UpdateMilestone(ctx context.Context, arg1 *milestone.Milestone) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMilestone", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMilestone indicates an expected call of UpdateMilestone.
func (mr *MockMilestoneServiceMockRecorder) UpdateMilestone(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMilestone", reflect.TypeOf((*MockMilestoneService)(nil).UpdateMilestone), ctx, arg1)
}
