// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services/reaction_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services/reaction_service.go -destination=mocks/core/ports/services/reaction_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	reaction "softpharos/internal/core/domain/reaction"

	gomock "go.uber.org/mock/gomock"
)

// MockReactionService is a mock of ReactionService interface.
type MockReactionService struct {
	ctrl     *gomock.Controller
	recorder *MockReactionServiceMockRecorder
	isgomock struct{}
}

// MockReactionServiceMockRecorder is the mock recorder for MockReactionService.
type MockReactionServiceMockRecorder struct {
	mock *MockReactionService
}

// NewMockReactionService creates a new mock instance.
func NewMockReactionService(ctrl *gomock.Controller) *MockReactionService {
	mock := &MockReactionService{ctrl: ctrl}
	mock.recorder = &MockReactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReactionService) EXPECT() *MockReactionServiceMockRecorder {
	return m.recorder
}

// CreateReaction mocks base method.
func (m *MockReactionService) CreateReaction(ctx context.Context, arg1 *reaction.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReaction", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReaction indicates an expected call of CreateReaction.
func (mr *MockReactionServiceMockRecorder) CreateReaction(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReaction", reflect.TypeOf((*MockReactionService)(nil).CreateReaction), ctx, arg1)
}

// DeleteReaction mocks base method.
func (m *MockReactionService) DeleteReaction(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReaction", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReaction indicates an expected call of DeleteReaction.
func (mr *MockReactionServiceMockRecorder) DeleteReaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReaction", reflect.TypeOf((*MockReactionService)(nil).DeleteReaction), ctx, id)
}

// GetAllReactions mocks base method.
func (m *MockReactionService) GetAllReactions(ctx context.Context) ([]reaction.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllReactions", ctx)
	ret0, _ := ret[0].([]reaction.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllReactions indicates an expected call of GetAllReactions.
func (mr *MockReactionServiceMockRecorder) GetAllReactions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllReactions", reflect.TypeOf((*MockReactionService)(nil).GetAllReactions), ctx)
}

// GetReactionByID mocks base method.
func (m *MockReactionService) GetReactionByID(ctx context.Context, id int) (*reaction.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReactionByID", ctx, id)
	ret0, _ := ret[0].(*reaction.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReactionByID indicates an expected call of GetReactionByID.
func (mr *MockReactionServiceMockRecorder) GetReactionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReactionByID", reflect.TypeOf((*MockReactionService)(nil).GetReactionByID), ctx, id)
}

// GetReactionsByMilestoneID mocks base method.
func (m *MockReactionService) GetReactionsByMilestoneID(ctx context.Context, milestoneID int) ([]reaction.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReactionsByMilestoneID", ctx, milestoneID)
	ret0, _ := ret[0].([]reaction.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReactionsByMilestoneID indicates an expected call of GetReactionsByMilestoneID.
func (mr *MockReactionServiceMockRecorder) GetReactionsByMilestoneID(ctx, milestoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReactionsByMilestoneID", reflect.TypeOf((*MockReactionService)(nil).GetReactionsByMilestoneID), ctx, milestoneID)
}

// UpdateReaction mocks base method.
func (m *MockReactionService) UpdateReaction(ctx context.Context, arg1 *reaction.Reaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReaction", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReaction indicates an expected call of UpdateReaction.
func (mr *MockReactionServiceMockRecorder) UpdateReaction(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReaction", reflect.TypeOf((*MockReactionService)(nil).UpdateReaction), ctx, arg1)
}
