// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services/feedback_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services/feedback_service.go -destination=mocks/core/ports/services/feedback_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	feedback "softpharos/internal/core/domain/feedback"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackService is a mock of FeedbackService interface.
type MockFeedbackService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackServiceMockRecorder
	isgomock struct{}
}

// MockFeedbackServiceMockRecorder is the mock recorder for MockFeedbackService.
type MockFeedbackServiceMockRecorder struct {
	mock *MockFeedbackService
}

// NewMockFeedbackService creates a new mock instance.
func NewMockFeedbackService(ctrl *gomock.Controller) *MockFeedbackService {
	mock := &MockFeedbackService{ctrl: ctrl}
	mock.recorder = &MockFeedbackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackService) EXPECT() *MockFeedbackServiceMockRecorder {
	return m.recorder
}

// CreateFeedback mocks base method.
func (m *MockFeedbackService) CreateFeedback(ctx context.Context, arg1 *feedback.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeedback", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFeedback indicates an expected call of CreateFeedback.
func (mr *MockFeedbackServiceMockRecorder) CreateFeedback(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeedback", reflect.TypeOf((*MockFeedbackService)(nil).CreateFeedback), ctx, arg1)
}

// DeleteFeedback mocks base method.
func (m *MockFeedbackService) DeleteFeedback(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeedback", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeedback indicates an expected call of DeleteFeedback.
func (mr *MockFeedbackServiceMockRecorder) DeleteFeedback(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeedback", reflect.TypeOf((*MockFeedbackService)(nil).DeleteFeedback), ctx, id)
}

// GetAllFeedbacks mocks base method.
func (m *MockFeedbackService) GetAllFeedbacks(ctx context.Context) ([]feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFeedbacks", ctx)
	ret0, _ := ret[0].([]feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFeedbacks indicates an expected call of GetAllFeedbacks.
func (mr *MockFeedbackServiceMockRecorder) GetAllFeedbacks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFeedbacks", reflect.TypeOf((*MockFeedbackService)(nil).GetAllFeedbacks), ctx)
}

// GetFeedbackByID mocks base method.
func (m *MockFeedbackService) GetFeedbackByID(ctx context.Context, id int) (*feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedbackByID", ctx, id)
	ret0, _ := ret[0].(*feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedbackByID indicates an expected call of GetFeedbackByID.
func (mr *MockFeedbackServiceMockRecorder) GetFeedbackByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedbackByID", reflect.TypeOf((*MockFeedbackService)(nil).GetFeedbackByID), ctx, id)
}

// GetFeedbacksByMilestoneID mocks base method.
func (m *MockFeedbackService) GetFeedbacksByMilestoneID(ctx context.Context, milestoneID int) ([]feedback.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedbacksByMilestoneID", ctx, milestoneID)
	ret0, _ := ret[0].([]feedback.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedbacksByMilestoneID indicates an expected call of GetFeedbacksByMilestoneID.
func (mr *MockFeedbackServiceMockRecorder) GetFeedbacksByMilestoneID(ctx, milestoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedbacksByMilestoneID", reflect.TypeOf((*MockFeedbackService)(nil).GetFeedbacksByMilestoneID), ctx, milestoneID)
}

// UpdateFeedback mocks base method.
func (m *MockFeedbackService) UpdateFeedback(ctx context.Context, arg1 *feedback.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeedback", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeedback indicates an expected call of UpdateFeedback.
func (mr *MockFeedbackServiceMockRecorder) UpdateFeedback(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeedback", reflect.TypeOf((*MockFeedbackService)(nil).UpdateFeedback), ctx, arg1)
}
