// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services/project_member_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services/project_member_service.go -destination=mocks/core/ports/services/project_member_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"
	project_member "softpharos/internal/core/domain/project_member"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectMemberService is a mock of ProjectMemberService interface.
type MockProjectMemberService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMemberServiceMockRecorder
	isgomock struct{}
}

// MockProjectMemberServiceMockRecorder is the mock recorder for MockProjectMemberService.
type MockProjectMemberServiceMockRecorder struct {
	mock *MockProjectMemberService
}

// NewMockProjectMemberService creates a new mock instance.
func NewMockProjectMemberService(ctrl *gomock.Controller) *MockProjectMemberService {
	mock := &MockProjectMemberService{ctrl: ctrl}
	mock.recorder = &MockProjectMemberServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMemberService) EXPECT() *MockProjectMemberServiceMockRecorder {
	return m.recorder
}

// CreateProjectMember mocks base method.
func (m *MockProjectMemberService) CreateProjectMember(ctx context.Context, projectMember *project_member.ProjectMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProjectMember", ctx, projectMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProjectMember indicates an expected call of CreateProjectMember.
func (mr *MockProjectMemberServiceMockRecorder) CreateProjectMember(ctx, projectMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProjectMember", reflect.TypeOf((*MockProjectMemberService)(nil).CreateProjectMember), ctx, projectMember)
}

// DeleteProjectMember mocks base method.
func (m *MockProjectMemberService) DeleteProjectMember(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectMember", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectMember indicates an expected call of DeleteProjectMember.
func (mr *MockProjectMemberServiceMockRecorder) DeleteProjectMember(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectMember", reflect.TypeOf((*MockProjectMemberService)(nil).DeleteProjectMember), ctx, id)
}

// GetAllProjectMembers mocks base method.
func (m *MockProjectMemberService) GetAllProjectMembers(ctx context.Context) ([]project_member.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProjectMembers", ctx)
	ret0, _ := ret[0].([]project_member.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProjectMembers indicates an expected call of GetAllProjectMembers.
func (mr *MockProjectMemberServiceMockRecorder) GetAllProjectMembers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProjectMembers", reflect.TypeOf((*MockProjectMemberService)(nil).GetAllProjectMembers), ctx)
}

// GetProjectMemberByID mocks base method.
func (m *MockProjectMemberService) GetProjectMemberByID(ctx context.Context, id int) (*project_member.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectMemberByID", ctx, id)
	ret0, _ := ret[0].(*project_member.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectMemberByID indicates an expected call of GetProjectMemberByID.
func (mr *MockProjectMemberServiceMockRecorder) GetProjectMemberByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectMemberByID", reflect.TypeOf((*MockProjectMemberService)(nil).GetProjectMemberByID), ctx, id)
}

// GetProjectMembersByProjectID mocks base method.
func (m *MockProjectMemberService) GetProjectMembersByProjectID(ctx context.Context, projectID int) ([]project_member.ProjectMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectMembersByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]project_member.ProjectMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectMembersByProjectID indicates an expected call of GetProjectMembersByProjectID.
func (mr *MockProjectMemberServiceMockRecorder) GetProjectMembersByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectMembersByProjectID", reflect.TypeOf((*MockProjectMemberService)(nil).GetProjectMembersByProjectID), ctx, projectID)
}

// UpdateProjectMember mocks base method.
func (m *MockProjectMemberService) UpdateProjectMember(ctx context.Context, projectMember *project_member.ProjectMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectMember", ctx, projectMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProjectMember indicates an expected call of UpdateProjectMember.
func (mr *MockProjectMemberServiceMockRecorder) UpdateProjectMember(ctx, projectMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectMember", reflect.TypeOf((*MockProjectMemberService)(nil).UpdateProjectMember), ctx, projectMember)
}
