CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" text,
  "created_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role_id" integer NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "projects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "objective" text,
  "created_by" integer NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "project_members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "role" varchar,
  "joined_at" timestamp
);

CREATE TABLE "milestones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" integer NOT NULL,
  "title" varchar,
  "description" text,
  "class_week" integer,
  "created_at" timestamp
);

CREATE TABLE "deliverables" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "url" text NOT NULL,
  "type" varchar,
  "created_at" timestamp
);

CREATE TABLE "feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "professor_id" integer NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "content" text,
  "created_at" timestamp
);

CREATE TABLE "reactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "type" varchar,
  "created_at" timestamp
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "project_members" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "milestones" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "deliverables" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestones" ("id");

ALTER TABLE "feedback" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestones" ("id");

ALTER TABLE "feedback" ADD FOREIGN KEY ("professor_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestones" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestones" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
