CREATE TABLE "role" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" text,
  "created_at" timestamp
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role_id" integer NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "project" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "objective" text,
  "created_by" integer NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "project_member" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "role" varchar,
  "joined_at" timestamp
);

CREATE TABLE "milestone" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" integer NOT NULL,
  "title" varchar,
  "description" text,
  "class_week" integer,
  "created_at" timestamp
);

CREATE TABLE "deliverable" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "url" text NOT NULL,
  "type" varchar,
  "created_at" timestamp
);

CREATE TABLE "feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "professor_id" integer NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "comment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "content" text,
  "created_at" timestamp
);

CREATE TABLE "reaction" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "milestone_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "type" varchar,
  "created_at" timestamp
);

ALTER TABLE "user" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "project" ADD FOREIGN KEY ("created_by") REFERENCES "user" ("id");

ALTER TABLE "project_member" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id");

ALTER TABLE "project_member" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "milestone" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id");

ALTER TABLE "deliverable" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestone" ("id");

ALTER TABLE "feedback" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestone" ("id");

ALTER TABLE "feedback" ADD FOREIGN KEY ("professor_id") REFERENCES "user" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestone" ("id");

ALTER TABLE "comment" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "reaction" ADD FOREIGN KEY ("milestone_id") REFERENCES "milestone" ("id");

ALTER TABLE "reaction" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
